name: "STAGING ENV: Snowflake Terraform Demo Workflow"

on: 
  push:
    branches: [ staging ]

jobs:
  deploy-terraform-staging:
    name: "Plan & Deploy Terraform plan on Staging"
    if: github.ref_name == "staging"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Format
        id: fmt
        run: terraform -chdir=./staging fmt -check

      - name: Terraform Init
        id: init
        run: terraform -chdir=./staging init

      - name: Terraform Validate
        id: validate
        run: terraform -chdir=./staging validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform -chdir=./staging plan 
        with:
          TF_VAR_snowflake_private_key: ${{ secrets.SNOWFLAKE_PRIVATE_KEY }}

      - name: Terraform Apply
        id: apply
        run: terraform -chdir=./staging apply -auto-approve
        with:
          TF_VAR_snowflake_private_key: ${{ secrets.SNOWFLAKE_PRIVATE_KEY }}
