name: "Production Workflow"

on:
  push:
    branches:
      - main
  pull_request:

env:
  TF_CLOUD_ORGANIZATION: sean-kim-demo-corp
  TF_WORKSPACE: PROD

jobs:
  snowflake-terraform-demo:
    name: "Snowflake Job on Prod"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init 

      - name: Terraform Validate
        id: validate
        run: |
          export SNOWFLAKE_ACCOUNT="${{ secrets.SNOWFLAKE_ACCOUNT }}"
          export SNOWFLAKE_REGION="${{ secrets.SNOWFLAKE_REGION }}"
          export SNOWFLAKE_USER="${{ secrets.SNOWFLAKE_USER }}"
          export SNOWFLAKE_PASSWORD="${{ secrets.SNOWFLAKE_PASSWORD }}"
          terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        continue-on-error: true

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Terraform Apply
        run: terraform apply -auto-approve